---
title: "Spotify Songs"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(tidyverse)
library(DT)
library(shiny)
library(ggplot2)
library(knitr)

dataPath <- 'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-21/spotify_songs.csv'
loadData <- function(dataPath){
  if (!exists("data/spotify_songs.csv")){
    system("mkdir -p data")
    spotify_songs <- readr::read_csv(dataPath)
    write.csv(spotify_songs, "data/spotify_songs.csv")
  }else{
    spotify_songs <- read.csv("data/spotify_songs.csv")
  }
  return(spotify_songs)
}
spotify <- loadData(dataPath)
```
About
=====================================  
    
Column {data-width=600}
-------------------------------------

The Data {data-orientation=rows}
=====================================     
   
Row {data-height=600}
-------------------------------------
### Taking a look at the data
```{r}
tableData <- spotify %>%
  select(!c(track_id, track_album_release_date, playlist_id, track_album_id))
DT::renderDataTable(tableData)
```


Interactive: Musical features by genre {data-orientation=rows}
=====================================     
   
Row {data-height=600}
-------------------------------------
Column {.sidebar}
-----------------------------------------------------------------------
```{r}
selectInput("genre", label = "Select a genre:",
            choices = unique(spotify$playlist_genre), selected = "rock")

```
Column {data-height=1000}
-----------------------------------------------------------------------
```{r}
renderPlot({genreFeats <- spotify %>%
  select(danceability, energy, speechiness, acousticness, liveness, instrumentalness, playlist_genre) %>%
  filter(playlist_genre==input$genre)%>%
  select(danceability, energy, speechiness, acousticness, liveness, instrumentalness) %>%
  colMeans()%>%
  as.data.frame() %>%
  rownames_to_column("feature") %>%
  rename("avg"= ".")
  p <- ggplot(genreFeats, aes(x=feature, y=avg))+
  geom_bar(stat="identity")+
  xlab("Musical Feature")+
  ylab("Average value")
  
  print(p)})
```
Interactive: Random song generator {data-orientation=rows}
=====================================     
   
Row {data-height=600}
-------------------------------------
Column {.sidebar}
-----------------------------------------------------------------------
```{r}
selectInput("genre2", label = "Select a genre to get a random song from that genre:",
            choices = unique(spotify$playlist_genre), selected = "rock")

```
Column {data-height=1000}
-----------------------------------------------------------------------
```{r}
renderText({
  songNames <- spotify %>%
    filter(playlist_genre == input$genre2)%>%
    select(track_name, track_artist)
  ind <- sample(1:length(songNames$track_name), 1)
  name <- songNames[[ind,1]]
  artist <- songNames[[ind,2]]
  print(paste(name, "by", artist))

})

```


Static:  {data-orientation=rows}
=====================================     
Column {.tabset}
-----------------------------------------------------------------------


### Popularity
```{r}
spotifyPop <- spotify %>%
  group_by(playlist_genre) %>%
  select(track_popularity, playlist_genre)%>%
  group_modify(~ as.data.frame(mean(.$track_popularity)))

colnames(spotifyPop) <- c("genre", "averagePop")

renderPlot({ggplot(spotifyPop, aes(x=genre, y=averagePop))+
  geom_bar(stat="identity")+
  xlab("Genre")+
  ylab("Average popularity")+
  ggtitle("Average popularity of songs in each genre")})
```


### Playlist

```{r, out.extra=c('allow="encrypted-media"', 'allowtransparency="true"', 'frameBorder="0"')}
knitr::include_url("https://open.spotify.com/embed/playlist/5uPUkCs6k2TvYc2RXjJjYs?utm_source=generator", height = "380")
```

Analysis {data-orientation=rows}
=====================================     
   
Row {data-height=600}
-------------------------------------
